### ISSUE TITLE
error from axios

### ISSUE THREAD

**Issue by harnie2275** [kudabank/openapi-node#13]
Error: Request failed with status code 400
    at createError (/Users/macbook/cashioApp/node_modules/kuda-node/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/macbook/cashioApp/node_modules/kuda-node/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/macbook/cashioApp/node_modules/kuda-node/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
undefined

after making a request to fetch the main account balance.

**Comment by harnie2275** [comment]
Hello,

After going to the code, and consoling the err.response the gave me invalid client has the error.message. What's should i do as regarding invalid client.

Here is my log:
{
  status: 400,
  statusText: 'Bad Request',
  headers: {
    date: 'Tue, 15 Mar 2022 21:31:47 GMT',
    'content-type': 'application/json; charset=utf-8',
    server: 'envoy',
    'x-envoy-upstream-service-time': '35',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      password: 'TiPun3ReTHgONAxcBKBmA6BYyMfvoTbQNXkUiKdo79MQicqyJNbLBIsTm6kkGVhPB7mOyPc8RwRUSz2ODeY7wkzB4eUKcczJDZAeFlyyUQlb/nOLVjpKjO25a/KefNh9FaX70ON1LtdFBff/SKV5HOQ+7ZRlJOn/EpCuXwpTrAs=',
      'User-Agent': 'axios/0.26.0',
      'Content-Length': 291
    },
    method: 'post',
    url: 'https://kuda-openapi-uat.kudabank.com/v1',
    data: '{"data":"LauaMG442Wl2vf065MNiZjaO/lnW4yanc8W2dmU+O/gYM0ZZykk3cR3ovDRYoN765JRMYLLyeqsdDH7P4U8bMGy5rULwsEboHrnDTYelxe/DtVFxXXBp2NFhDnQIxYqAmJ0b7BBaYbztdjVyD4bmvkouSDyR44N556YkqpSJADX58KrScDN7W1xhSb82irR/vbGLBr4HMSdUTkXVqe5Qmn18HE49/XBJpZ3rEV8muJRzKKW1fngDZhCuk1G8t7xxB1VYtbXtfq36awmCgCCNRA=="}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'kuda-openapi-uat.kudabank.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'kuda-openapi-uat.kudabank.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 29,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /v1 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'password: TiPun3ReTHgONAxcBKBmA6BYyMfvoTbQNXkUiKdo79MQicqyJNbLBIsTm6kkGVhPB7mOyPc8RwRUSz2ODeY7wkzB4eUKcczJDZAeFlyyUQlb/nOLVjpKjO25a/KefNh9FaX70ON1LtdFBff/SKV5HOQ+7ZRlJOn/EpCuXwpTrAs=\r\n' +
      'User-Agent: axios/0.26.0\r\n' +
      'Content-Length: 291\r\n' +
      'Host: kuda-openapi-uat.kudabank.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/v1',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://kuda-openapi-uat.kudabank.com/v1',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 12,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'kuda-openapi-uat.kudabank.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 291,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://kuda-openapi-uat.kudabank.com/v1',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      password: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  data: { message: 'Invalid Client' }
}
Error: Request failed with status code 400
    at createError (/Users/macbook/cashioApp/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/macbook/cashioApp/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/macbook/cashioApp/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
undefined
listening at port 5000
[nodemon] restarting due to changes...
[nodemon] starting `node index.js`
listening at port 5000
{
  status: 400,
  statusText: 'Bad Request',
  headers: {
    'transfer-encoding': 'chunked',
    'content-type': 'application/json; charset=utf-8',
    server: 'Microsoft-IIS/10.0',
    'strict-transport-security': 'max-age=2592000',
    'x-powered-by': 'ASP.NET',
    'set-cookie': [
      'ARRAffinity=382356a2c77720b36614ec9681903c554d967a79b823fc8ad90081b622b87501;Path=/;HttpOnly;Secure;Domain=kudaopenapi.azurewebsites.net',
      'ARRAffinitySameSite=382356a2c77720b36614ec9681903c554d967a79b823fc8ad90081b622b87501;Path=/;HttpOnly;SameSite=None;Secure;Domain=kudaopenapi.azurewebsites.net'
    ],
    date: 'Tue, 15 Mar 2022 21:34:47 GMT',
    connection: 'close'
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      password: 'T1xRPBCWZzsQ5EAZ7BjfE29jvFwHFfZrpVrr2q5CPCGLQYhgo9QLF/1tQ5MGP+x8t2spO5wKnpwzQMa40n+4N/VVF8Tf8sSxNnqPBU6xF5QWBe9SLSsodyqchfUglU9bs53UuQbl2DB2MPYkhWdE0a6cjGBJBauRA5+0ZumSrYc=',
      'User-Agent': 'axios/0.26.0',
      'Content-Length': 291
    },
    method: 'post',
    url: 'https://kudaopenapi.azurewebsites.net/v1',
    data: '{"data":"qdrOqbEnKwv/xTTGa803ybEsxn/BBBiZdDyGkvO5JCtYRzkOveBiGufJ6q0RHO4rho/HdWD3v4W6PVRYWVaRqiySM1lyaFnFBve8ujMY1JTyu32SQPuExZHy04YfxZCf6zujagoFDzKE9OIUbssGZ0XmlnYRCRaEsEGCAR8iHD0BAzo8Fn7ymL0mBsFHNBvq5TpsNysdrEKiv4JIWtGZuiG2xlXDlfX8WiPym1T7imAFRMW+G+fzGJUftrAqDWrToS0kXE3farorP9dAijUFCA=="}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'kudaopenapi.azurewebsites.net',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'kudaopenapi.azurewebsites.net',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 29,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /v1 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'password: T1xRPBCWZzsQ5EAZ7BjfE29jvFwHFfZrpVrr2q5CPCGLQYhgo9QLF/1tQ5MGP+x8t2spO5wKnpwzQMa40n+4N/VVF8Tf8sSxNnqPBU6xF5QWBe9SLSsodyqchfUglU9bs53UuQbl2DB2MPYkhWdE0a6cjGBJBauRA5+0ZumSrYc=\r\n' +
      'User-Agent: axios/0.26.0\r\n' +
      'Content-Length: 291\r\n' +
      'Host: kudaopenapi.azurewebsites.net\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/v1',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://kudaopenapi.azurewebsites.net/v1',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 18,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'kudaopenapi.azurewebsites.net',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 291,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://kudaopenapi.azurewebsites.net/v1',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      password: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  data: { message: 'Invalid Client' }
}

**Comment by harnie2275** [comment]
Hey,

I fixed it, it was misleading/outdated GitHub documentation. The client key should be the one on your developer.kudabank.com/dashboard account and not your private key file name

**Comment by michael-azogu** [comment]
Amazing error
